COMP = gcc
FLAGS = -Wall -pedantic-errors

compile:
	$(COMP) $(FLAGS) -o head head.c
	$(COMP) $(FLAGS) -o true true.c
	$(COMP) $(FLAGS) -o false false.c
	$(COMP) $(FLAGS) -o wc wc.c
clean:
	rm -f head
	rm -f true
	rm -f false
	rm -f wc
